apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwtSigningKeySecret.name }}
type: Opaque
stringData:
  {{ .Values.jwtSigningKeySecret.key }}: "CHANGE_ME_MIN_32_CHARS________________________"
